# Generated by Django 5.1.5 on 2025-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('descriptions', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='img')),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
